### ISSUE TITLE
yarnrc fails to create a new profile

### ISSUE THREAD

**Issue by ralvez** [vitorcamachoo/yarnrc#1]
From Usage instructions: "Calling yarnrc without arguments creates an ~/.yarnrcs/ directory if it doesn't exist, and copies your current ~/.yarnrc as the 'default' .yarnrc profile."

But in my case it does not. The response is: /usr/bin/env: ‘node\r’: No such file or directory

If I instead use :  yarnrc -c newprofile I get : bash: /home/myuser: Is a directory

Could this be related to the fact that my global npm repository is ~/home/myuser/.node_modules_global instead of default used by node?
I've changed it to avoid having to use sudo every time I want to install a global package.
I use ArchLinx and I've have an up-to-date system.

**Comment by Vitorcamacho** [comment]
Sorry to know that, but unfortunately I work over a windows environment and I use default settings. Probably it can be related with what you specified. This repo is strongly attached into [npmrc](https://github.com/deoxxa/npmrc), so, maybe you could open an issue there.
From what I've read in npmrc repository, it can related with permissions.

**Comment by ralvez** [comment]
Thanks for the reply. 
I think that it would be rather odd if I make an issue for yarnrc in npmrc regardless of how related they are.
I'll just remove yarnrc and wait until it is a bit more mature to try it again.

Thanks again.

**Comment by Vitorcamacho** [comment]
I think you should  try the same with npmrc module to find if the same issue happens. If not, I will take a look.

**Comment by ralvez** [comment]
I **am** using npmrc and the issue is not there... that's the reason I posted the message. In other words, npmrc works as expected with a "custom" global storage.
I figured that if both modules are similar the behavior should be similar too.

**Comment by Vitorcamacho** [comment]
I've released a new version which fixed your issue. It was related with line break type that was defined in IDE.
